language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
install:
    - if [[ ${TRAVIS_PYTHON_VERSION:0:1} == 2 ]]; then pip install unittest2; fi
    - pip install -r requirements.txt
    - apt-get update -qq
    - apt-get install libboost-dev
    - python setup.py install
script:
    - nosetests